[package]
name = "jwt-signing-verify-presigned-jsonwebtoken"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
bench-harness = { path = "../../../../../harness/rust", features = ["operations"] }
jsonwebtoken = { version = "11", default-features = false, features = ["rust_crypto"] }
serde_json = "1"
